// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWzcG2kwWEUuY77hNaUQJ0CbLratRUDT0',
    appId: '1:834162821648:web:32d973036be247c2605895',
    messagingSenderId: '834162821648',
    projectId: 'chat-b08f1',
    authDomain: 'chat-b08f1.firebaseapp.com',
    storageBucket: 'chat-b08f1.appspot.com',
    measurementId: 'G-PKJG303JH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD113oHchEL4qH8u7qNHysEDn8hkyQL218',
    appId: '1:834162821648:android:6960df95d6681f6c605895',
    messagingSenderId: '834162821648',
    projectId: 'chat-b08f1',
    storageBucket: 'chat-b08f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfjPzAC7uh-dWRsppEIuh8q1MnRsyTt40',
    appId: '1:834162821648:ios:af5d4f255e022c56605895',
    messagingSenderId: '834162821648',
    projectId: 'chat-b08f1',
    storageBucket: 'chat-b08f1.appspot.com',
    androidClientId: '834162821648-0roi1hlle49q7t749b34oaa4sfg44iva.apps.googleusercontent.com',
    iosClientId: '834162821648-vpn8fncmgf50rebpssmmsrkla1qkrssm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfjPzAC7uh-dWRsppEIuh8q1MnRsyTt40',
    appId: '1:834162821648:ios:c0d4d300ec2c93cd605895',
    messagingSenderId: '834162821648',
    projectId: 'chat-b08f1',
    storageBucket: 'chat-b08f1.appspot.com',
    androidClientId: '834162821648-0roi1hlle49q7t749b34oaa4sfg44iva.apps.googleusercontent.com',
    iosClientId: '834162821648-ijhfkjn0umh3ctdhvt7ud1rnq29hlqli.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
